export const links = {
    'AQI TW': 'https://airtw.moenv.gov.tw/',
    'Algo Ans': 'https://walkccc.me/CLRS/',
    'Anigamer': 'https://ani.gamer.com.tw/',
    'Calendar': 'https://calendar.google.com/calendar/u/0/r',
    'ChatGPT': 'https://chat.openai.com/',
    'Colab':
        'https://colab.research.google.com/drive/1c56LHV9HmUk_IMPTMROKPGCe-vUsvOGQ',
    'Coolor': 'https://coolors.co/',
    'Dam': 'https://www.clubdam.com/',
    'Discord': 'https://discord.com/channels/@me',
    'Doc': 'https://docs.google.com/document/u/0/',
    'Drive': 'https://drive.google.com/drive/u/0/home',
    'Expatrio':
        'https://www.expatrio.com/xp/?utm_campaign=TXN%20CN%20Simplified&utm_medium=email&_hsenc=p2ANqtz-99Eu_URxi74qOvo4YBjK-gUGWWkcIQasPBDZzR9gD9Tjrlg8EB8weZ4JmCEieO12pWo7zbHXc5os3y9CkQmRMTP_QCjg&_hsmi=265426476&utm_content=265426476&utm_source=hs_automation#/login?redirect_url=https%3A%2F%2Fwww.expatrio.com%2Fxp%2F%3Futm_campaign%3DTXN%2520CN%2520Simplified%26utm_medium%3Demail%26_hsenc%3Dp2ANqtz-99Eu_URxi74qOvo4YBjK-gUGWWkcIQasPBDZzR9gD9Tjrlg8EB8weZ4JmCEieO12pWo7zbHXc5os3y9CkQmRMTP_QCjg%26_hsmi%3D265426476%26utm_content%3D265426476%26utm_source%3Dhs_automation%23%2Flogin',
    'Facebook': 'https://zh-tw.facebook.com/',
    'Famiport': 'https://www.famiport.com.tw/Web_Famiport/page/cloudprint.aspx',
    'Flowchart': 'https://app.diagrams.net/',
    'Font': 'https://fonts.google.com/',
    'Font Awesome': 'https://fontawesome.com/icons',
    'Gemini': 'https://gemini.google.com/app',
    'GitHub': 'https://github.com/',
    'Gmail': 'https://mail.google.com/mail/u/0/#inbox',
    'Group': 'https://groups.google.com/u/0/g/nmsl-all/c/AsGZhi2lT5s',
    'HackMD': 'https://hackmd.io/?nav=overview',
    'Haikei': 'https://app.haikei.app/',
    'Hololive': 'https://hololive.hololivepro.com/en/talents',
    'Instagram': 'https://www.instagram.com/',
    'JP Space':
        'https://hackmd.io/@tropical08842/B1_YN_-kp/https%3A%2F%2Fhackmd.io%2F%40tropical08842%2FHJEHlK-kT%2F%252Fp7Ti7wARSoq9GKGdiLh0xg',
    'LeetCode': 'https://leetcode.com/problemset/',
    'Line of Action': 'https://line-of-action.com/',
    'Lucide': 'https://lucide.dev/icons/',
    'Maps': 'https://www.google.com/maps/',
    'Mathpix': 'https://snip.mathpix.com/home',
    'Messenger': 'https://www.messenger.com/',
    'NMSL': 'https://nmsl.cs.nthu.edu.tw/cs5262-schedule-2024/',
    'OJAD': 'https://www.gavo.t.u-tokyo.ac.jp/ojad/phrasing/',
    'Overleaf': 'https://www.overleaf.com/project',
    'PCRD Pickup': 'https://forum.gamer.com.tw/C.php?bsn=30861&snA=27653',
    'PCRD PvP': 'https://pcrdfans.com/battle',
    'Past Exam':
        'https://drive.google.com/drive/folders/1zoRayCwbnTJIZ_WJSXRyR0Z5-BThec8X',
    'Pinterest': 'https://www.pinterest.com/',
    'Pixiv': 'https://www.pixiv.net/',
    'Presentation': 'https://hsiii.github.io/Presentation',
    'Quickposes': 'https://quickposes.com/en/gestures/timed',
    'React dev': 'http://localhost:3000/',
    'SSTM': 'https://hackmd.io/@sessatakuma/%E8%AD%B0%E4%BA%8B%E9%8C%B2',
    'SSTM dev': 'http://localhost:8080/',
    'Sheet': 'https://docs.google.com/spreadsheets/u/0/',
    'Slide': 'https://docs.google.com/presentation/u/0/',
    'Spotify': 'https://open.spotify.com/',
    'Squoosh': 'https://squoosh.app/',
    'Stylish': 'https://userstyles.org/',
    'TUCaN':
        'https://www.tucan.tu-darmstadt.de/scripts/mgrqispi.dll?APPNAME=CampusNet&PRGNAME=ACTION&ARGUMENTS=-A6-VkjuH-iRdxtcbUbsSwYyOYZhdqMJDQOCdoK1J-iuohpKVkbk4j6SVfVmPt6fAJu43JVC19q10MMNNT8aOL6-3RWt~L4wVJFuXwGJWSs1kEU6ibMllhU1rWF2sWLrm8XoUsylSK1Mvzv5Z2IPE1U7W6mT90jfDTFoBroshCATeT562F-9B27YdtR27UBEhDGh-GOXqGeeU7PHU_',
    'Tetr.io': 'https://tetr.io',
    'Train':
        'https://tip.railway.gov.tw/tra-tip-web/tip/tip001/tip112/gobytime',
    'Translate': 'https://translate.google.com/',
    'Twitter': 'https://twitter.com/home',
    'Unix': 'https://hackmd.io/@Koios/ryGcbe3R2/%2F%40Koios%2F3YUbrErzRt-xYy--2Pd_Hg',
    'Utaten': 'https://utaten.com/search',
    'Vue dev': 'http://localhost:5173/',
    'YouTube': 'https://www.youtube.com/',
    'ccxp': 'https://www.ccxp.nthu.edu.tw/ccxp/INQUIRE/',
    'eeclass':
        'https://oauth.ccxp.nthu.edu.tw/v1.1/authorize.php?response_type=code&client_id=eeclass&redirect_uri=https%3A%2F%2Feeclass.nthu.edu.tw%2Fservice%2Foauth%2F&scope=lmsid+userid&state=&ui_locales=zh-TW',
    'elearn':
        'https://oauth.ccxp.nthu.edu.tw/v1.1/authorize.php?client_id=elearn&response_type=code&redirect_uri=https%3A%2F%2Felearn.nthu.edu.tw%2Fadmin%2Foauth2callback.php&state=%2Fauth%2Foauth2%2Flogin.php%3Fwantsurl%3Dhttps%253A%252F%252Felearn.nthu.edu.tw%252F%26sesskey%3DqqdzzWqh7e%26id%3D5&scope=userid%20name%20email%20lmsid',
    'maimai': 'https://maimaidx-eng.com/maimai-mobile/home/',
    'refern': 'https://my.refern.app/',
};
