export const links = {
    'AkuMa': 'https://accent-marker.sessatakuma.dev/',
    'Algo Ans': 'https://walkccc.me/CLRS/',
    'Anigamer': 'https://ani.gamer.com.tw/',
    'AQI TW': 'https://airtw.moenv.gov.tw/',
    'Awwwards': 'https://www.awwwards.com/',
    'Badgical': 'https://badgical.hsichen.dev',
    'Calendar': 'https://calendar.google.com/calendar/u/0/r',
    'ccxp': 'https://www.ccxp.nthu.edu.tw/ccxp/INQUIRE/',
    'ChatGPT': 'https://chat.openai.com/',
    'Cloudflare': 'https://dash.cloudflare.com/',
    'Coliss': 'https://coliss.com/articles/freebies/japanese-free-fonts.html',
    'Coolor': 'https://coolors.co/',
    'Crx': 'https://chrome.google.com/webstore/devconsole/',
    'Dam': 'https://www.clubdam.com/',
    'Discord': 'https://discord.com/channels/@me',
    'Doc': 'https://docs.google.com/document/u/0/',
    'Drive': 'https://drive.google.com/drive/u/0/home',
    'eeclass': 'https://eeclass.nthu.edu.tw/',
    'Expatrio':
        'https://www.expatrio.com/xp/?utm_campaign=TXN%20CN%20Simplified&utm_medium=email&_hsenc=p2ANqtz-99Eu_URxi74qOvo4YBjK-gUGWWkcIQasPBDZzR9gD9Tjrlg8EB8weZ4JmCEieO12pWo7zbHXc5os3y9CkQmRMTP_QCjg&_hsmi=265426476&utm_content=265426476&utm_source=hs_automation#/login?redirect_url=https%3A%2F%2Fwww.expatrio.com%2Fxp%2F%3Futm_campaign%3DTXN%2520CN%2520Simplified%26utm_medium%3Demail%26_hsenc%3Dp2ANqtz-99Eu_URxi74qOvo4YBjK-gUGWWkcIQasPBDZzR9gD9Tjrlg8EB8weZ4JmCEieO12pWo7zbHXc5os3y9CkQmRMTP_QCjg%26_hsmi%3D265426476%26utm_content%3D265426476%26utm_source%3Dhs_automation%23%2Flogin',
    'Facebook': 'https://zh-tw.facebook.com/',
    'Famiport': 'https://www.famiport.com.tw/Web_Famiport/page/cloudprint.aspx',
    'Figma': 'https://www.figma.com/files/team/',
    'Flowchart': 'https://app.diagrams.net/',
    'Font': 'https://fonts.google.com/',
    'Font Awesome': 'https://fontawesome.com/icons',
    'Gemini': 'https://gemini.google.com/app',
    'GitHub': 'https://github.com/',
    'Gmail': 'https://mail.google.com/mail/u/0/#inbox',
    'Group': 'https://groups.google.com/u/0/g/nmsl-all/c/AsGZhi2lT5s',
    'HackMD': 'https://hackmd.io/?nav=overview',
    'Haikei': 'https://app.haikei.app/',
    'Head Ref': 'https://www.artstation.com/artwork/GX3Ax1',
    'Hololive Ref': 'https://hololive.hololivepro.com/en/talents',
    'Instagram': 'https://www.instagram.com/',
    'JP Space':
        'https://hackmd.io/@tropical08842/B1_YN_-kp/https%3A%2F%2Fhackmd.io%2F%40tropical08842%2FHJEHlK-kT%2F%252Fp7Ti7wARSoq9GKGdiLh0xg',
    'LeetCode': 'https://leetcode.com/problemset/',
    'Line of Action': 'https://line-of-action.com/',
    'Lucide': 'https://lucide.dev/icons/',
    'maimai': 'https://maimaidx-eng.com/maimai-mobile/home/',
    'maimaiJP': 'https://maimaidx.jp/',
    'Maps': 'https://www.google.com/maps/',
    'Mathpix': 'https://snip.mathpix.com/home',
    'Messenger': 'https://www.messenger.com/',
    'Motion': 'https://motion.zajno.com/',
    'Moz Add-on': 'https://addons.mozilla.org/en-US/developers/addons',
    'NMSL': 'https://nmsl.cs.nthu.edu.tw/cs5262-schedule-2024/',
    'NotebookLM': 'https://notebooklm.google.com/',
    'Overleaf': 'https://www.overleaf.com/project',
    'Past Exam':
        'https://drive.google.com/drive/folders/1zoRayCwbnTJIZ_WJSXRyR0Z5-BThec8X',
    'PCRD Pickup': 'https://forum.gamer.com.tw/C.php?bsn=30861&snA=27653',
    'PCRD PvP': 'https://pcrdfans.com/battle',
    'Pinterest': 'https://www.pinterest.com/',
    'Pixiv': 'https://www.pixiv.net/',
    'Pose Ref': 'https://pt.pinterest.com/kloezzs/poses/1/',
    'Quickposes': 'https://quickposes.com/en/gestures/timed',
    'refern': 'https://my.refern.app/',
    'Repomux': 'https://repomux.hsichen.dev/',
    'Resource Boy': 'https://resourceboy.com/',
    'Search Console': 'https://search.google.com/search-console/welcome',
    'Sheet': 'https://docs.google.com/spreadsheets/u/0/',
    'Skyscanner': 'https://www.skyscanner.com/',
    'Slide': 'https://docs.google.com/presentation/u/0/',
    'Spotify': 'https://open.spotify.com/',
    'Squoosh': 'https://squoosh.app/',
    'SSTM': 'https://docs.sessatakuma.dev/doc/',
    'SSTM dev': 'http://localhost:8080/',
    'Supabase': 'https://supabase.com/dashboard/org/csgiyguemdbvpbvaprgx',
    'Supercell Store': 'https://store.supercell.com/brawlstars',
    'Svgl': 'https://svgl.app/',
    'Tetr.io': 'https://tetr.io',
    'Texturelabs': 'https://texturelabs.org/',
    'Train':
        'https://tip.railway.gov.tw/tra-tip-web/tip/tip001/tip112/gobytime',
    'Translate': 'https://translate.google.com/',
    'TUCaN':
        'https://www.tucan.tu-darmstadt.de/scripts/mgrqispi.dll?APPNAME=CampusNet&PRGNAME=ACTION&ARGUMENTS=-A6-VkjuH-iRdxtcbUbsSwYyOYZhdqMJDQOCdoK1J-iuohpKVkbk4j6SVfVmPt6fAJu43JVC19q10MMNNT8aOL6-3RWt~L4wVJFuXwGJWSs1kEU6ibMllhU1rWF2sWLrm8XoUsylSK1Mvzv5Z2IPE1U7W6mT90jfDTFoBroshCATeT562F-9B27YdtR27UBEhDGh-GOXqGeeU7PHU_',
    'Twitter': 'https://twitter.com/home',
    'Unix': 'https://hackmd.io/@Koios/ryGcbe3R2/%2F%40Koios%2F3YUbrErzRt-xYy--2Pd_Hg',
    'Utaten': 'https://utaten.com/search',
    'Vercel': 'https://vercel.com/',
    'Vue dev': 'http://localhost:5173/',
    'WebGradients': 'https://webgradients.com/',
    'wordmark': 'https://wordmark.it/',
    'YouTube': 'https://www.youtube.com/',
} as const satisfies Record<string, string>;

export type LinkName = keyof typeof links;
