export const links = {
    elearn: 'https://oauth.ccxp.nthu.edu.tw/v1.1/authorize.php?client_id=elearn&response_type=code&redirect_uri=https%3A%2F%2Felearn.nthu.edu.tw%2Fadmin%2Foauth2callback.php&state=%2Fauth%2Foauth2%2Flogin.php%3Fwantsurl%3Dhttps%253A%252F%252Felearn.nthu.edu.tw%252F%26sesskey%3DqqdzzWqh7e%26id%3D5&scope=userid%20name%20email%20lmsid',
    eeclass:
        'https://oauth.ccxp.nthu.edu.tw/v1.1/authorize.php?response_type=code&client_id=eeclass&redirect_uri=https%3A%2F%2Feeclass.nthu.edu.tw%2Fservice%2Foauth%2F&scope=lmsid+userid&state=&ui_locales=zh-TW',
    ccxp: 'https://www.ccxp.nthu.edu.tw/ccxp/INQUIRE/',
    Facebook: 'https://zh-tw.facebook.com/',
    Messenger: 'https://www.messenger.com/',
    Discord: 'https://discord.com/channels/@me',
    Twitter: 'https://twitter.com/home',
    Pixiv: 'https://www.pixiv.net/',
    YouTube: 'https://www.youtube.com/',
    Gmail: 'https://mail.google.com/mail/u/0/#inbox',
    GGroup: 'https://groups.google.com/u/0/g/nmsl-all/c/AsGZhi2lT5s',
    NMSL: 'https://nmsl.cs.nthu.edu.tw/cs5262-schedule-2024/',
    'JP Space':
        'https://hackmd.io/@tropical08842/B1_YN_-kp/https%3A%2F%2Fhackmd.io%2F%40tropical08842%2FHJEHlK-kT%2F%252Fp7Ti7wARSoq9GKGdiLh0xg',
    GitHub: 'https://github.com/',
    HackMD: 'https://hackmd.io/?nav=overview',
    'Past Exam':
        'https://drive.google.com/drive/folders/0B9qFeq29tGaLVndza2FqSmttNjQ?resourcekey=0-ktN_SgGqiMEhH009dMuc3g&fbclid=IwAR3n0MchvVMuW2L00QnRu0C_9ot9UmdvFwHbQUsJ1UrEglTLwfTbEZnsupg',
    Colab: 'https://colab.research.google.com/drive/1c56LHV9HmUk_IMPTMROKPGCe-vUsvOGQ',
    'Font Awesome': 'https://fontawesome.com/icons',
    'G-Font': 'https://fonts.google.com/',
    Stylish: 'https://userstyles.org/',
    'G-Calendar': 'https://calendar.google.com/calendar/u/0/r',
    'G-Slide': 'https://docs.google.com/presentation/u/0/',
    'G-Sheet': 'https://docs.google.com/spreadsheets/u/0/',
    Flowchart: 'https://app.diagrams.net/',
    Train: 'https://tip.railway.gov.tw/tra-tip-web/tip/tip001/tip112/gobytime',
    Hololive: 'https://hololive.hololivepro.com/en/talents',
    Anigamer: 'https://ani.gamer.com.tw/',
    Pinterest: 'https://www.pinterest.com/',
    Utaten: 'https://utaten.com/search',
    Dam: 'https://www.clubdam.com/',
    maimai: 'https://maimaidx-eng.com/maimai-mobile/home/',
    'PCRD PvP': 'https://pcrdfans.com/battle',
    'PCRD Pickup': 'https://forum.gamer.com.tw/C.php?bsn=30861&snA=27653',
    'Algo Ans': 'https://walkccc.me/CLRS/',
    Unix: 'https://hackmd.io/@Koios/ryGcbe3R2/%2F%40Koios%2F3YUbrErzRt-xYy--2Pd_Hg',
    'G-Doc': 'https://docs.google.com/document/u/0/',
    Famiport: 'https://www.famiport.com.tw/Web_Famiport/page/cloudprint.aspx',
    'G-Translate': 'https://translate.google.com/',
    ChatGPT: 'https://chat.openai.com/',
    'AQI TW': 'https://airtw.moenv.gov.tw/',
    Overleaf: 'https://www.overleaf.com/project',
    TUCaN: 'https://www.tucan.tu-darmstadt.de/scripts/mgrqispi.dll?APPNAME=CampusNet&PRGNAME=ACTION&ARGUMENTS=-A6-VkjuH-iRdxtcbUbsSwYyOYZhdqMJDQOCdoK1J-iuohpKVkbk4j6SVfVmPt6fAJu43JVC19q10MMNNT8aOL6-3RWt~L4wVJFuXwGJWSs1kEU6ibMllhU1rWF2sWLrm8XoUsylSK1Mvzv5Z2IPE1U7W6mT90jfDTFoBroshCATeT562F-9B27YdtR27UBEhDGh-GOXqGeeU7PHU_',
    LeetCode: 'https://leetcode.com/problemset/',
    refern: 'https://my.refern.app/',
    Quickposes: 'https://quickposes.com/en/gestures/timed',
    'Tetr.io': 'https://tetr.io',
    Expatrio:
        'https://www.expatrio.com/xp/?utm_campaign=TXN%20CN%20Simplified&utm_medium=email&_hsenc=p2ANqtz-99Eu_URxi74qOvo4YBjK-gUGWWkcIQasPBDZzR9gD9Tjrlg8EB8weZ4JmCEieO12pWo7zbHXc5os3y9CkQmRMTP_QCjg&_hsmi=265426476&utm_content=265426476&utm_source=hs_automation#/login?redirect_url=https%3A%2F%2Fwww.expatrio.com%2Fxp%2F%3Futm_campaign%3DTXN%2520CN%2520Simplified%26utm_medium%3Demail%26_hsenc%3Dp2ANqtz-99Eu_URxi74qOvo4YBjK-gUGWWkcIQasPBDZzR9gD9Tjrlg8EB8weZ4JmCEieO12pWo7zbHXc5os3y9CkQmRMTP_QCjg%26_hsmi%3D265426476%26utm_content%3D265426476%26utm_source%3Dhs_automation%23%2Flogin',
    'G-Drive': 'https://drive.google.com/drive/u/0/home',
    'Line of Action': 'https://line-of-action.com/',
    OJAD: 'https://www.gavo.t.u-tokyo.ac.jp/ojad/phrasing/',
    SSTM: 'https://hackmd.io/@sessatakuma/%E8%AD%B0%E4%BA%8B%E9%8C%B2',
    'React dev': 'http://localhost:3000/',
    'Vue dev': 'http://localhost:5173/',
    'SSTM dev': 'http://localhost:8080/',
    Haikei: 'https://app.haikei.app/',
    Mathpix: 'https://snip.mathpix.com/home',
    Coolor: 'https://coolors.co/',
    Squoosh: 'https://squoosh.app/',
    Presentation: 'https://hsiii.github.io/Presentation',
};
